#!/usr/bin/env python3
"""Safe helper for the ZeloDesk declarative cloud deployment.

This script runs locally. It does not run Docker Compose on your workstation.
Docker Compose is executed remotely by Ansible on the ECS instances.
"""

from __future__ import annotations

import argparse
import base64
import getpass
import http.client
import json
import os
import secrets
import shutil
import stat
import subprocess
import sys
from pathlib import Path
from urllib import error, parse, request


ROOT = Path(__file__).resolve().parent
TERRAFORM_DIR = ROOT / "terraform"
ANSIBLE_DIR = ROOT / "ansible"
INVENTORY = ANSIBLE_DIR / "inventory.ini"
ANSIBLE_ALL_VARS = ANSIBLE_DIR / "group_vars" / "all.yml"
JENKINS_VARS = ANSIBLE_DIR / "group_vars" / "jenkins.yml"
GENERATED_TERRAFORM_VARS = TERRAFORM_DIR / "generated.auto.tfvars"
EPHEMERAL_SSH_ARGS = "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def run(command: list[str], cwd: Path | None = None, capture: bool = False) -> subprocess.CompletedProcess[str]:
    if not capture:
        location = f" in {cwd}" if cwd else ""
        print(f"$ {' '.join(command)}{location}")

    try:
        return subprocess.run(
            command,
            cwd=str(cwd) if cwd else None,
            text=True,
            check=True,
            stdout=subprocess.PIPE if capture else None,
            stderr=subprocess.PIPE if capture else None,
        )
    except FileNotFoundError:
        fail(f"command not found: {command[0]}")
    except subprocess.CalledProcessError as exc:
        if capture:
            if exc.stdout:
                print(exc.stdout, file=sys.stderr)
            if exc.stderr:
                print(exc.stderr, file=sys.stderr)
        fail(f"command failed: {' '.join(command)}")


def require_commands(commands: list[str]) -> None:
    missing = [command for command in commands if shutil.which(command) is None]
    if missing:
        fail(f"missing required command(s): {', '.join(missing)}")


def confirm(prompt: str, assume_yes: bool = False, default: bool = False) -> bool:
    if assume_yes:
        return True

    suffix = "[Y/n]" if default else "[y/N]"
    answer = input(f"{prompt} {suffix} ").strip().lower()
    if not answer:
        return default
    return answer in {"y", "yes", "s", "sim"}


def terraform_output(name: str) -> str:
    result = run(["terraform", "-chdir=terraform", "output", "-raw", name], cwd=ROOT, capture=True)
    value = result.stdout.strip()
    if not value:
        fail(f"Terraform output {name!r} is empty. Did terraform apply finish successfully?")
    return value


def terraform_env_value(name: str) -> str | None:
    try:
        result = run(["terraform", "-chdir=terraform", "output", "-raw", "application_env"], cwd=ROOT, capture=True)
    except SystemExit:
        return None

    for line in result.stdout.splitlines():
        key, separator, value = line.partition("=")
        if separator and key == name:
            return value
    return None


def write_if_changed(path: Path, content: str, assume_yes: bool, mode: int | None = None) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    current = path.read_text() if path.exists() else None

    if current == content:
        print(f"unchanged: {path.relative_to(ROOT)}")
        if mode is not None:
            os.chmod(path, mode)
        return False

    if current is not None and not confirm(f"overwrite {path.relative_to(ROOT)}?", assume_yes):
        print(f"kept existing: {path.relative_to(ROOT)}")
        return False

    path.write_text(content)
    if mode is not None:
        os.chmod(path, mode)
    print(f"wrote: {path.relative_to(ROOT)}")
    return True


def yaml_string(value: str) -> str:
    return json.dumps(value)


def remove_if_exists(path: Path) -> None:
    if path.exists():
        path.unlink()
        print(f"removed: {path.relative_to(ROOT)}")


def clean_generated_config(include_terraform_vars: bool = True) -> None:
    remove_if_exists(INVENTORY)
    remove_if_exists(ANSIBLE_ALL_VARS)
    remove_if_exists(JENKINS_VARS)
    if include_terraform_vars:
        remove_if_exists(GENERATED_TERRAFORM_VARS)


def configure_terraform_password(password: str, assume_yes: bool) -> None:
    content = f"""# Generated by deploy.py. This file is ignored by Git.
ecs_admin_password = {yaml_string(password)}
rds_admin_password = {yaml_string(password)}
client_secret      = {yaml_string(password)}
"""
    write_if_changed(GENERATED_TERRAFORM_VARS, content, assume_yes, mode=stat.S_IRUSR | stat.S_IWUSR)


def configure_ansible_password(password: str, assume_yes: bool) -> None:
    content = f"""# Generated by deploy.py. This file is ignored by Git.
ansible_password: {yaml_string(password)}
"""
    write_if_changed(ANSIBLE_ALL_VARS, content, assume_yes, mode=stat.S_IRUSR | stat.S_IWUSR)


def configure_inventory(assume_yes: bool, deploy_password: str | None) -> dict[str, str]:
    outputs = {
        "ecs_ssh_eip": terraform_output("ecs_ssh_eip"),
        "jenkins_ssh_eip": terraform_output("jenkins_ssh_eip"),
        "public_url": terraform_output("public_url"),
        "jenkins_url": terraform_output("jenkins_url"),
        "jenkins_webhook_url": terraform_output("jenkins_webhook_url"),
    }

    inventory = f"""[zelodesk]
zelodesk-ecs ansible_host={outputs['ecs_ssh_eip']} ansible_user=root ansible_ssh_common_args='{EPHEMERAL_SSH_ARGS}'

[jenkins]
jenkins-ecs ansible_host={outputs['jenkins_ssh_eip']} ansible_user=root ansible_ssh_common_args='{EPHEMERAL_SSH_ARGS}'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
"""

    write_if_changed(INVENTORY, inventory, assume_yes)
    if deploy_password:
        configure_ansible_password(deploy_password, assume_yes)
    return outputs


def read_existing_jenkins_password() -> bool:
    if not JENKINS_VARS.exists():
        return False
    text = JENKINS_VARS.read_text()
    return "CHANGE_ME_Strong_Jenkins_123!" not in text and "jenkins_admin_password" in text


def prompt_jenkins_password() -> str:
    env_password = os.environ.get("JENKINS_ADMIN_PASSWORD")
    if env_password:
        return env_password

    if not sys.stdin.isatty():
        generated = secrets.token_urlsafe(24)
        print("generated a Jenkins admin password because stdin is not interactive")
        print(f"Jenkins admin password: {generated}")
        return generated

    while True:
        password = getpass.getpass("Jenkins admin password to write to ansible/group_vars/jenkins.yml: ")
        if not password:
            if confirm("generate a random Jenkins admin password instead?", default=True):
                generated = secrets.token_urlsafe(24)
                print(f"Jenkins admin password: {generated}")
                return generated
            continue

        confirm_password = getpass.getpass("repeat Jenkins admin password: ")
        if password == confirm_password:
            return password
        print("passwords did not match")


def configure_jenkins_vars(
    assume_yes: bool,
    github_repo: str,
    github_branch: str,
    force_password: bool,
    deploy_password: str | None,
) -> None:
    if read_existing_jenkins_password() and not force_password and deploy_password is None:
        print(f"kept existing: {JENKINS_VARS.relative_to(ROOT)}")
        os.chmod(JENKINS_VARS, stat.S_IRUSR | stat.S_IWUSR)
        return

    if JENKINS_VARS.exists() and not force_password and deploy_password is None:
        print("existing Jenkins vars contain the placeholder password")

    password = deploy_password or prompt_jenkins_password()
    content = f"""# Generated by deploy.py. This file is ignored by Git.
jenkins_admin_user: "admin"
jenkins_admin_password: {yaml_string(password)}

github_repo_url: {yaml_string(github_repo)}
github_repo_branch: {yaml_string(github_branch)}

jenkins_dir: "/opt/zelodesk-jenkins"
terraform_dir: "{{{{ playbook_dir }}}}/../terraform"
"""

    write_if_changed(JENKINS_VARS, content, assume_yes, mode=stat.S_IRUSR | stat.S_IWUSR)


def terraform_apply(assume_yes: bool, deploy_password: str | None) -> None:
    require_commands(["terraform"])
    if deploy_password:
        configure_terraform_password(deploy_password, assume_yes)

    if not confirm("run terraform init/apply? this can create or change paid cloud resources", assume_yes):
        print("skipped terraform apply")
        return

    run(["terraform", "init"], cwd=TERRAFORM_DIR)
    command = ["terraform", "apply"]
    if assume_yes:
        command.append("-auto-approve")
    run(command, cwd=TERRAFORM_DIR)


def terraform_destroy(assume_yes: bool, deploy_password: str | None) -> None:
    require_commands(["terraform"])
    if deploy_password:
        configure_terraform_password(deploy_password, assume_yes)

    if not confirm("destroy Terraform deployment and delete local generated config? this can delete paid cloud resources and data", assume_yes):
        print("skipped terraform destroy")
        return

    run(["terraform", "init"], cwd=TERRAFORM_DIR)
    command = ["terraform", "destroy"]
    if assume_yes:
        command.append("-auto-approve")
    run(command, cwd=TERRAFORM_DIR)
    clean_generated_config()


def terraform_reset(assume_yes: bool, deploy_password: str | None) -> None:
    require_commands(["terraform"])
    if deploy_password:
        configure_terraform_password(deploy_password, assume_yes)

    if not confirm("reset Terraform deployment from zero? this will destroy and recreate paid cloud resources and data", assume_yes):
        print("skipped terraform reset")
        return

    clean_generated_config(include_terraform_vars=False)
    run(["terraform", "init"], cwd=TERRAFORM_DIR)

    destroy_command = ["terraform", "destroy"]
    apply_command = ["terraform", "apply"]
    if assume_yes:
        destroy_command.append("-auto-approve")
        apply_command.append("-auto-approve")

    run(destroy_command, cwd=TERRAFORM_DIR)
    run(apply_command, cwd=TERRAFORM_DIR)


def run_playbook(playbook: str, assume_yes: bool, deploy_password: str | None) -> None:
    require_commands(["ansible-playbook"])
    if not INVENTORY.exists():
        fail("ansible/inventory.ini does not exist. Run configuration first.")

    playbook_path = ANSIBLE_DIR / playbook
    if not playbook_path.exists():
        fail(f"missing playbook: {playbook_path}")

    command = ["ansible-playbook", "-i", "inventory.ini", playbook]
    if deploy_password is None:
        command.append("--ask-pass")
    run(command, cwd=ANSIBLE_DIR)


def deploy_password_from_args(args: argparse.Namespace) -> str | None:
    password = args.password or os.environ.get("ZELODESK_DEPLOY_PASSWORD")
    if password == "":
        fail("deployment password cannot be empty")
    return password


def read_generated_jenkins_password() -> str | None:
    if not JENKINS_VARS.exists():
        return None

    for line in JENKINS_VARS.read_text().splitlines():
        key, separator, value = line.partition(":")
        if separator and key == "jenkins_admin_password":
            return value.strip().strip('"') or None
    return None


def http_check(name: str, url: str, method: str = "GET", headers: dict[str, str] | None = None, body: bytes | None = None) -> None:
    http_request = request.Request(url, data=body, headers=headers or {}, method=method)
    try:
        with request.urlopen(http_request, timeout=15) as response:
            print(f"{name}: HTTP {response.status} {response.reason} ({url})")
    except error.HTTPError as exc:
        print(f"{name}: HTTP {exc.code} {exc.reason} ({url})")
    except (error.URLError, TimeoutError, http.client.HTTPException, OSError) as exc:
        reason = getattr(exc, "reason", exc)
        print(f"{name}: unreachable ({reason}) ({url})")


def run_status_command(name: str, command: list[str], cwd: Path) -> None:
    print(f"\n{name}")
    try:
        result = subprocess.run(command, cwd=str(cwd), text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=90)
    except FileNotFoundError:
        print(f"skipped: command not found: {command[0]}")
        return
    except subprocess.TimeoutExpired:
        print("failed: command timed out")
        return

    if result.stdout.strip():
        print(result.stdout.strip())
    if result.stderr.strip():
        print(result.stderr.strip())
    if result.returncode != 0:
        print(f"failed: exit code {result.returncode}")


def deployment_status(deploy_password: str | None) -> None:
    require_commands(["terraform"])

    print("Terraform outputs")
    outputs: dict[str, str] = {}
    for name in ["public_url", "jenkins_url", "ecs_ssh_eip", "jenkins_ssh_eip"]:
        try:
            outputs[name] = terraform_output(name)
            print(f"{name}: {outputs[name]}")
        except SystemExit:
            print(f"{name}: unavailable")

    public_url = outputs.get("public_url")
    jenkins_url = outputs.get("jenkins_url")

    print("\nHTTP checks")
    if public_url:
        http_check("app", public_url)
        http_check("app token endpoint without credentials (401 is expected)", f"{public_url.rstrip('/')}/api/oauth2/token")
        client_secret = deploy_password or terraform_env_value("CLIENT_SECRET")
        if client_secret:
            credentials = base64.b64encode(f"zelodesk-client:{client_secret}".encode()).decode()
            body = parse.urlencode({
                "grant_type": "password",
                "username": "solicitante@zelodesk.com",
                "password": "123456",
                "scope": "read write",
            }).encode()
            http_check(
                "app login token",
                f"{public_url.rstrip('/')}/api/oauth2/token",
                method="POST",
                headers={
                    "Authorization": f"Basic {credentials}",
                    "Content-Type": "application/x-www-form-urlencoded",
                },
                body=body,
            )
        else:
            print("app login token: skipped (CLIENT_SECRET unavailable)")
    if jenkins_url:
        http_check("jenkins root without login (403 is expected)", jenkins_url)
        http_check("jenkins login", f"{jenkins_url.rstrip('/')}/login")
        jenkins_password = read_generated_jenkins_password()
        if jenkins_password:
            credentials = base64.b64encode(f"admin:{jenkins_password}".encode()).decode()
            http_check("jenkins authenticated API", f"{jenkins_url.rstrip('/')}/whoAmI/api/json", headers={"Authorization": f"Basic {credentials}"})
        else:
            print("jenkins authenticated API: skipped (generated Jenkins password unavailable)")

    if not INVENTORY.exists():
        print("\nAnsible checks skipped: ansible/inventory.ini does not exist")
        return
    if shutil.which("ansible") is None:
        print("\nAnsible checks skipped: ansible command not found")
        return

    run_status_command("Ansible ping", ["ansible", "-i", "inventory.ini", "all", "-m", "ping"], ANSIBLE_DIR)
    run_status_command("Application containers", ["ansible", "-i", "inventory.ini", "zelodesk", "-m", "command", "-a", "docker ps"], ANSIBLE_DIR)
    run_status_command("Jenkins containers", ["ansible", "-i", "inventory.ini", "jenkins", "-m", "command", "-a", "docker ps -a"], ANSIBLE_DIR)
    run_status_command("Jenkins Allure CLI", ["ansible", "-i", "inventory.ini", "jenkins", "-m", "command", "-a", "docker exec zelodesk-jenkins /opt/allure-2.40.0/bin/allure --version"], ANSIBLE_DIR)


def print_summary(outputs: dict[str, str] | None) -> None:
    if outputs is None:
        try:
            outputs = {
                "public_url": terraform_output("public_url"),
                "jenkins_url": terraform_output("jenkins_url"),
                "jenkins_webhook_url": terraform_output("jenkins_webhook_url"),
            }
        except SystemExit:
            return

    print("\nDeployment URLs")
    print(f"app:             {outputs['public_url']}")
    print(f"jenkins:         {outputs['jenkins_url']}")
    print(f"github webhook:  {outputs['jenkins_webhook_url']}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Configure and run the ZeloDesk Terraform + Ansible cloud deployment from the repo root.",
    )
    parser.add_argument("--up", action="store_true", help="run Terraform apply and the full Ansible deploy")
    parser.add_argument("--down", action="store_true", help="destroy Terraform resources and delete generated local config")
    parser.add_argument("--status", action="store_true", help="check Terraform outputs, HTTP endpoints, SSH and remote containers")
    parser.add_argument("--apply-terraform", action="store_true", help="run terraform init/apply before configuring Ansible")
    parser.add_argument("--reset-terraform", action="store_true", help="destroy and recreate Terraform resources before configuring Ansible")
    parser.add_argument("--configure-only", action="store_true", help="only generate local Ansible config files; do not run playbooks")
    parser.add_argument("--app-only", action="store_true", help="run only the application playbook")
    parser.add_argument("--jenkins-only", action="store_true", help="run only the Jenkins playbook")
    parser.add_argument("--yes", "-y", action="store_true", help="answer yes to overwrite/apply/run prompts")
    parser.add_argument("--password", help="use one password for ECS SSH, RDS, Jenkins and generated app secrets")
    parser.add_argument("--force-jenkins-password", action="store_true", help="replace existing ansible/group_vars/jenkins.yml password")
    parser.add_argument("--github-repo", default="https://github.com/araujoviana/lab-eng-software-grupo10.git", help="GitHub repo URL used by the Jenkins job")
    parser.add_argument("--github-branch", default="main", help="Git branch used by the Jenkins job")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    os.chdir(ROOT)
    deploy_password = deploy_password_from_args(args)

    if not TERRAFORM_DIR.exists() or not ANSIBLE_DIR.exists():
        fail("run this script from the repository root, with terraform/ and ansible/ present")

    require_commands(["terraform"])

    if args.status:
        deployment_status(deploy_password)
        return

    if args.down:
        terraform_destroy(args.yes, deploy_password)
        return

    if args.reset_terraform:
        terraform_reset(args.yes, deploy_password)
    elif args.apply_terraform or args.up:
        terraform_apply(args.yes, deploy_password)

    print("configuring local Ansible files from Terraform outputs")
    outputs = configure_inventory(args.yes, deploy_password)

    if not args.app_only:
        configure_jenkins_vars(args.yes, args.github_repo, args.github_branch, args.force_jenkins_password, deploy_password)
    else:
        print("skipped Jenkins vars because --app-only was used")

    if args.configure_only:
        print_summary(outputs)
        return

    selected_app = args.app_only or not args.jenkins_only
    selected_jenkins = args.jenkins_only or not args.app_only

    if selected_app and confirm("run application Ansible deploy now?", args.yes):
        run_playbook("playbook.yml", args.yes, deploy_password)

    if selected_jenkins and confirm("run Jenkins Ansible deploy now?", args.yes):
        run_playbook("jenkins.yml", args.yes, deploy_password)

    print_summary(outputs)


if __name__ == "__main__":
    main()
