# Banco H2 em mem�ria para testes
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Deixa o JPA criar/dropar o schema automaticamente
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Desativa Flyway nos testes (H2 n�o usa as migra��es Postgres)
spring.flyway.enabled=false

