spring.profiles.active=${APP_PROFILE:test}

spring.jpa.open-in-view=false

security.client-id=${CLIENT_ID:myclientid}
security.client-secret=${CLIENT_SECRET:myclientsecret}

security.jwt.duration=${JWT_DURATION:86400}

cors.origins=${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/zelodeskdb
spring.datasource.username=zelouser
spring.datasource.password=zelouser
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
